### ISSUE TITLE
Error when running in systemjs-builder

### ISSUE THREAD

**Issue by Rush** [johnsoftek/plugin-jade#10]
when calling `builder.buildSFX()`

```
[04:31:59] 'requirejs:setup' errored after 2.39 s
[04:31:59] Error: Error: /code/frontend/node_modules/systemjs-builder/node_modules/systemjs/dist/system.src.js:2798
          throw new Error('Module not already loaded loading "' + names + '" f
                ^
Module not already loaded loading "fs" from "undefined".
        Evaluating file:///code/frontend/.gulp-build/jspm_packages/github/johnsoftek/plugin-jade@0.5.1/jade.js
        Evaluating file:///code/frontend/.gulp-build/jspm_packages/github/johnsoftek/plugin-jade@0.5.1.js
        Error loading file:///code/frontend/.gulp-build/jspm_packages/github/johnsoftek/plugin-jade@0.5.1.js
    at formatError (/home/rush/.nvm/v0.12.7/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/home/rush/.nvm/v0.12.7/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.emit (events.js:107:17)
    at Gulp.Orchestrator._emitTaskDone (/home/rush/.nvm/v0.12.7/lib/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /home/rush/.nvm/v0.12.7/lib/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/home/rush/.nvm/v0.12.7/lib/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at /home/rush/.nvm/v0.12.7/lib/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:45:4
    at lib$rsvp$$internal$$tryCatch (/code/frontend/node_modules/systemjs-builder/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/code/frontend/node_modules/systemjs-builder/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/code/frontend/node_modules/systemjs-builder/node_modules/rsvp/dist/rsvp.js:476:11)
```

**Comment by johnsoftek** [comment]
This error may be related to #8. Module fs is unavailable during bundling. What version of Systemjs are you using?

**Comment by johnsoftek** [comment]
No activity. Closing old issue.
