### ISSUE TITLE
can not use extends

### ISSUE THREAD

**Issue by kirly-af** [johnsoftek/plugin-jade#18]
I get the following error when using `extends`

```
Error: Jade:1
      > 1| extends core/_layout.jade
        2| 

    the "filename" option is required to use "extends" with "relative" paths
        at Parser.resolvePath (http://localhost:8080/jspm_packages/npm/jade@1.11.0/lib/parser.js:486:13)
        at Parser.parseExtends (http://localhost:8080/jspm_packages/npm/jade@1.11.0/lib/parser.js:505:21)
        at Parser.parseExpr (http://localhost:8080/jspm_packages/npm/jade@1.11.0/lib/parser.js:221:21)
        at Parser.parse (http://localhost:8080/jspm_packages/npm/jade@1.11.0/lib/parser.js:122:25)
        at parse (http://localhost:8080/jspm_packages/npm/jade@1.11.0/lib/index.js:104:21)
        at Object.exports.compileClientWithDependenciesTracked (http://localhost:8080/jspm_packages/npm/jade@1.11.0/lib/index.js:256:16)
        at Object.exports.compileClient (http://localhost:8080/jspm_packages/npm/jade@1.11.0/lib/index.js:289:18)
        at eval (http://localhost:8080/jspm_packages/github/johnsoftek/plugin-jade@1.1.2/jade.js!transpiled:113:30)
```

**Comment by johnsoftek** [comment]
Extend is not supported in Jade-plugin.
The Jade compiler uses the fs module to read include and extend files. fs
isn't supported in the browser or in the bundler.
I did implement includes when requested by another plugin user. I will
examine extends to see how much work it would entail.
