### ISSUE TITLE
fs.realpathSync is not a function

### ISSUE THREAD

**Issue by marc1404** [johnsoftek/plugin-jade#22]
Using: `plugin-jade@1.1.2`

Stack trace:

```
Error: (SystemJS) fs.realpathSync is not a function  
    TypeError: fs.realpathSync is not a function  
        at eval (http://localhost:8100/jspm_packages/npm/uglify-js@2.2.5/tools/node.js:36:38)  
        at Array.map (native)  
        at Object.eval (http://localhost:8100/jspm_packages/npm/uglify-js@2.2.5/tools/node.js:35:3)  
        at eval (http://localhost:8100/jspm_packages/npm/uglify-js@2.2.5/tools/node.js:166:4)  
        at eval (http://localhost:8100/jspm_packages/npm/uglify-js@2.2.5/tools/node.js:167:3)  
    Evaluating http://localhost:8100/jspm_packages/npm/uglify-js@2.2.5/tools/node.js  
    Evaluating http://localhost:8100/jspm_packages/npm/transformers@2.1.0/lib/transformers.js  
    Evaluating http://localhost:8100/jspm_packages/npm/jade@1.11.0/lib/filters.js  
    Evaluating http://localhost:8100/jspm_packages/npm/jade@1.11.0/lib/parser.js  
    Evaluating http://localhost:8100/jspm_packages/npm/jade@1.11.0/lib/index.js  
    Error loading http://localhost:8100/jspm_packages/github/johnsoftek/plugin-jade@1.1.2/jade.js  
    Error loading http://localhost:8100/app/directives/document_uploader/document_uploader.jade as "./document_uploader.jade" from http://localhost:8100/app/directives/document_uploader/document_uploader_directive.js
```

Import statement:
`import { html as template } from './document_uploader.jade';`

jspm config:

```
"meta": {
        "*.jade": {
          "loader": "jade"
        },
```

**Comment by johnsoftek** [comment]
@marc1404 Are you using a file reference such as extends?

**Comment by marc1404** [comment]
The template is not using `extends` but `include` instead. Is this the cause of the problem?
